package me.dio.audioglow.domain.dto;

import java.time.Instant;

/**
 * Public API response for a processed voice command.
 *
 * @param textoTranscrito text produced from audio transcription
 * @param respostaIA answer generated by the AI model
 * @param timestamp processing completion timestamp
 */
public record VoiceAssistantResponse(
        String textoTranscrito,
        String respostaIA,
        Instant timestamp
) {
}
